#!/usr/bin/env sh
rm -f dist/carpo
rm -f dist/app.zip
go build -ldflags "-X main.carpo_version=`date +%s`" -o dist/carpo_raw
cd ../qx/carpo
./generate build
cd build
zip -r ../../../cmd/dist/app.zip * -x *ace-builds*
cd ../../../cmd/dist
cat carpo_raw app.zip > carpo
zip -A carpo
chmod 755 carpo

