#!/usr/bin/env sh
rm dist/carpo
rm dist/app.zip
go build -o dist/carpo_raw
cd ../qx/carpo
./generate build
cd build
zip -r ../../../cmd/dist/app.zip *
cd ../../../cmd/dist
cat carpo_raw app.zip > carpo
zip -A carpo
chmod 755 carpo

